### ISSUE TITLE
Wrong "ready to merge status" on pull requests

### ISSUE THREAD

**Issue by kevin-brown** [kevin-brown/github-support-tickets#1]
We use [protected branches and required status checks](https://github.com/blog/2051-protected-branches-and-required-status-checks) for a few things, and they've been working out great... for those of us who are administrators. We have checks enabled, so non-admins cannot merge pull requests if they are failing builds, and nobody can force-push to the master branch (yay!).

![image](https://cloud.githubusercontent.com/assets/1991850/12097206/5017da90-b2e8-11e5-8dd4-21f65a777525.png)

For those of us who are administrators, everything looks fine when there is a pull request with failing status checks.

![image](https://cloud.githubusercontent.com/assets/1991850/12097101/c84a19fc-b2e7-11e5-9cc0-038a40f11f24.png)

But for those who aren't administrators? Well, they are just told that their branch is not up to date. We can reproduce this issue by setting "Include administrators" in the protected branch settings.

![image](https://cloud.githubusercontent.com/assets/1991850/12097121/e0f9dec4-b2e7-11e5-9730-5aaf6e019a2d.png)

---

This issue also extends to branches with passing status checks. For administrators, they just see a pull request that is up to date, all status checks are passing, and is ready to merge.

![image](https://cloud.githubusercontent.com/assets/1991850/12097166/1849f0d0-b2e8-11e5-9b90-b64a32fdb2c0.png)

But non-administrators? They just see a pull request which is out of date with the latest master.

![image](https://cloud.githubusercontent.com/assets/1991850/12097135/f43a0b9e-b2e7-11e5-8d17-9f1a709a51a3.png)

Now, this one is tricky. The pull request actually isn't up to date with the base branch, but GitHub isn't warning us if we are an administrator and can override the protection. Both of these images are from the same pull request, the only difference is the "Include administrators" setting has been checked for the last one.

**Comment by kevin-brown** [comment]
Got the first reply last night

> Hi Kevin,
> 
> Sorry for the delay in getting back to you! I just wanted to reach out and let you know that we are looking into this and will update you as soon as we have more to share.
> 
> In the meantime, if you notice anything else about this unexpected behavior with the merge status of a PR for admins vs non-admins please let us know.
> 
> Cheers,
> Alex

**Comment by kevin-brown** [comment]
And the second reply about 30 minutes ago

> Hi Kevin,
> 
> Thanks for your patience while I looked into this. Unfortunately, I'm having some trouble replicating this exact behavior.
> 
> Do you by chance have an open PR where this behavior is occurring that I could take a look at?
> 
> Cheers,
> Alex

**Comment by kevin-brown** [comment]
Hi Alex,

I just created a new repository to test this issue on, you can see the pull request at https://github.com/kevin-brown/pr-status-test/pull/1

These are roughly the steps I took to confirm the two issues:
1. Create the repository (or use an existing repository)
2. Ensure the repository has a commit in the base branch
3. Set up a third-party integration which use status checks (I picked Travis CI, but I've seen it happen with others)
4. Create a new branch from the base branch
5. Commit to the branch (make sure it will fail the status checks)
6. Create a pull request from the new branch to the base branch
7. Wait for the status checks to fail

So at this point you should have a pull request with failing status checks that can still be merged because it does not conflict with the base branch. Because no protection has been set up yet, it should only give a warning (about the failing status checks, but there shouldn't be an issue).
1. Protect the base branch, require status checks to pass (not including administrators)

The pull request should still show up as being able to merge, almost as if you didn't set up protection in the first place.
1. Include administrators in the branch protection

You should now see an error saying that "This branch is out-of-date with the base branch", and the pull request can no longer be merged automatically. While the pull request shouldn't be merged, it's because the status checks failed. Not because the branch is out of date.
1. Push a new commit to the base branch (make sure it doesn't conflict with the PR, I created a new file)

The pull request should continue to not let you merge the branch, because the pull request is _now_ out of date with the base branch. This failure is expected.
1. Change the protection to no longer include administrators

The pull request should go back to the warning state, but it should still say that there are no conflicts with the base branch. While this _is_ true, it hides the fact that the pull request branch is out of date with the base branch, so the commit status checks aren't accurate. The pull request can still be merged.

Kevin

**Comment by kevin-brown** [comment]
Got another reply last night

> Hi Kevin,
> 
> Thanks very much for sending over those detailed reproduction steps! We've passed your feedback and notes around this over to our engineering team to take a look at and we'll reach out if we need any more information.
> 
> In the meantime, if you have any further details to share please just let us know.
> 
> Cheers,
> Alex

**Comment by ctruzzi** [comment]
Has there been any update? Facing a similar issue with frequently updated repository using a third-party integration tool. By the time the testing is completed the branch is almost always out of date.

**Comment by kevin-brown** [comment]
@ctruzzi Unfortunately I haven't heard back about this, but even once it is fixed you will still have to deal with the branch being out of date. The problem right now is that administrators are not given the same warning about the branch being out of date if they aren't required to have the status checks pass.

**Comment by nickmshelley** [comment]
I'm running into this as well. Pretty annoying.

**Comment by ctruzzi** [comment]
@kevin-brown You're right we actually facing the opposite issue as ours is tests take too long to run and create a loop of needing to update and currently using admins ability to by-pass the 'update branch' to resolve this issue temporarily.

**Comment by ryangribble** [comment]
any updates on this?  We've just encountered the same situation... We are on GitHub Enterprise 2.5 and I see that 2.5.1 has just been released... need to see whether that contains a fix or not

**Comment by kevin-brown** [comment]
Looks like this issue was fixed a few days ago, administrators now see the warning that the branch is out-of-date.

**Comment by ryangribble** [comment]
Thanks for the update!  
We're on github enterprise and can confirm as of updating to latest 2.5.1 this issue still exists. If it's fixed on cloud hopefully it'll be in 2.5.2 and hopefully that's not too far away

**Comment by nightpool** [comment]
This is still happening to me in certain cases, on cloud github. Is anyone still experiencing this?

**Comment by kevin-brown** [comment]
@nightpool I haven't seen this issue come up recently. What are you seeing on your end that appears to be a bug?

**Comment by nightpool** [comment]
Nevermind, I think I get it now. Branches with protected status checks have stricter guidelines on what github considers "automatically mergeable"—it will only merge PRs that are _up-to-date_, not just ones that merge cleanly.

**Comment by nightpool** [comment]
see also: https://help.github.com/articles/types-of-required-status-checks/
